version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            -   .:/app
        depends_on:
            -   db

    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: human_resources
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: ZXC123Asd!
        volumes:
            -   ./storage/dbdata:/var/lib/mysql
        ports:
            -   "33066:3306"
